#!/usr/bin/env php
<?php
if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
}
else if (file_exists(__DIR__.'/../../../vendor/autoload.php')){
    require __DIR__.'/../../../vendor/autoload.php';
}
else {
    require __DIR__.'/vendor/autoload.php';
}
$app = new Symfony\Component\Console\Application('Saas Installer', '1.3.1');
$app->add(new \Saas\Installer\InstallerCommand());
$app->add(new \Saas\Installer\SetupEnvCommand());
$app->add(new \Saas\Installer\InputLicenceCommand());
$app->run();